# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  portfolio.local:
    site_hosts:
      - canonical: portfolio.local
    local_path: ../bedrock # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: gregory@thecommodoredesigns.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    xmlrpc:
      enabled: false
